repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: migrations
        args: [--line-length=120]
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: bash -c "PWD=$(pwd) && export PYTHONPATH=\"${PYTHONPATH}:${PWD}\" && ./env/bin/pytest"
  #       exclude: ^migrations
  #       language: system
  #       types: [python]
  #       args: [--config=.flake8]
