services:
  web:
    container_name: aiohttp-web-api
    build: .
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    image: "postgres:14.10-alpine3.19"
    restart: always
    environment:
      POSTGRES_DB: dummy
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   restart: unless-stopped

volumes:
  postgres:
  # pgadmin: