services:
  api:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - postgres-network
      - redis-network
    # command: bash -c "cd .. && alembic upgrade head"

  postgres:
    image: "postgres:14.10-alpine3.19"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres-network

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data/redis
    networks:
      - redis-network

networks:
  postgres-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  postgres:
  redis:
