name: Check Format Code

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    name: Check Format Code
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check flake8
        run: |
          python -m flake8 ./src --count --show-source --statistics
      - name: Check pylint
        run: |
          python -m pylint ./src
      - name: Check isort
        run: |
          python -m isort --check-only ./src
      - name: Check format black
        run: |
          python -m black --check ./src
